const { makeWASocket, useMultiFileAuthState, DisconnectReason } = require('@whiskeysockets/baileys');
const QRCode = require('qrcode');
const path = require('path');
const fs = require('fs');
const pino = require('pino');

let sock = null;
let qrCodeData = null;
let connectionStatus = 'DISCONNECTED';
let lastError = null;
let isInitializing = false;

const initialize = async (force = false) => {
  if (isInitializing) return;
  if (sock && !force && connectionStatus !== 'DISCONNECTED') return;

  if (force) {
    await logout();
  }

  isInitializing = true;
  connectionStatus = 'INITIALIZING';
  lastError = null;
  qrCodeData = null;
  console.log('\n🤖 WhatsApp: Starting client initialization with Baileys...');

  try {
    const authDir = path.join(__dirname, '../../.baileys_auth');
    if (!fs.existsSync(authDir)) {
      fs.mkdirSync(authDir, { recursive: true });
    }

    const { state, saveCreds } = await useMultiFileAuthState(authDir);

    sock = makeWASocket({
      auth: state,
      printQRInTerminal: false,
      logger: pino({ level: 'silent' }),
      browser: ['UCK Academy', 'Chrome', '1.0.0'],
      connectTimeoutMs: 60000,
      defaultQueryTimeoutMs: 60000,
      keepAliveIntervalMs: 25000,
    });

    sock.ev.on('creds.update', saveCreds);

    sock.ev.on('connection.update', async (update) => {
      const { connection, lastDisconnect, qr } = update;

      if (qr) {
        console.log('🤖 WhatsApp: QR Code generated by Baileys!');
        try {
          qrCodeData = await QRCode.toDataURL(qr);
          connectionStatus = 'QR_READY';
          lastError = null;
        } catch (qrErr) {
          console.error('QR code conversion error:', qrErr);
        }
      }

      if (connection === 'close') {
        const statusCode = lastDisconnect?.error?.output?.statusCode;
        const shouldReconnect = statusCode !== DisconnectReason.loggedOut;
        console.log(`🤖 WhatsApp Connection closed. Reason code: ${statusCode}. Reconnecting: ${shouldReconnect}`);

        if (statusCode === DisconnectReason.loggedOut) {
          console.log('🤖 WhatsApp: User logged out. Clearing session files.');
          await logout();
        } else {
          connectionStatus = 'DISCONNECTED';
          qrCodeData = null;
          sock = null;
        }
      } else if (connection === 'open') {
        console.log('🤖 WhatsApp: Connection established! Baileys is READY.');
        connectionStatus = 'CONNECTED';
        qrCodeData = null;
        lastError = null;
      }
    });
  } catch (err) {
    console.error('❌ WhatsApp Baileys setup error:', err);
    connectionStatus = 'DISCONNECTED';
    lastError = err.message || 'Failed to initialize WhatsApp';
    qrCodeData = null;
    sock = null;
  } finally {
    isInitializing = false;
  }
};

const getStatus = () => connectionStatus;
const getQR = () => qrCodeData;
const getError = () => lastError;

const sendReminder = async (phone, message) => {
  if (connectionStatus !== 'CONNECTED' || !sock) {
    throw new Error('WhatsApp client is not connected');
  }

  let formattedNumber = phone.replace(/\D/g, '');
  
  // Handle Sri Lanka phone numbers (e.g. 0771234567 -> 94771234567, or 771234567 -> 94771234567)
  if (formattedNumber.startsWith('0') && formattedNumber.length === 10) {
    formattedNumber = '94' + formattedNumber.slice(1);
  } else if (formattedNumber.length === 9) {
    formattedNumber = '94' + formattedNumber;
  }

  const jid = `${formattedNumber}@s.whatsapp.net`;
  
  console.log(`🤖 WhatsApp: Sending message via Baileys to ${jid}...`);
  const result = await sock.sendMessage(jid, { text: message });
  console.log(`✅ WhatsApp: Sent message successfully to ${jid}`);
  return result;
};

const logout = async () => {
  if (sock) {
    try {
      await sock.logout();
    } catch (e) {
      console.log('Baileys logout info:', e.message);
    }
    try {
      sock.end(undefined);
    } catch (e) {}
  }
  sock = null;
  connectionStatus = 'DISCONNECTED';
  qrCodeData = null;

  const authDir = path.join(__dirname, '../../.baileys_auth');
  if (fs.existsSync(authDir)) {
    try {
      fs.rmSync(authDir, { recursive: true, force: true });
      console.log('🤖 WhatsApp: Session folder removed successfully.');
    } catch (e) {
      console.error('Failed to remove auth dir:', e);
    }
  }
};

module.exports = {
  initialize,
  getStatus,
  getQR,
  getError,
  sendReminder,
  logout
};

